//! Reading past dialogues out of Claude Code's own transcripts. tech.md 6.11.
//!
//! The registry is fed by hooks and lives in memory, so it knows nothing about
//! a session that ran before the app started, and a restart empties it. Claude
//! Code keeps that history on disk anyway, one JSON record per line, and this
//! module turns those files into cards.
//!
//! Read only, and only to fill gaps: a card that arrived over a hook is never
//! replaced by one from a file.

use std::path::{Path, PathBuf};

use serde_json::Value;

use crate::sessions::{ENTRY_CAP, SESSION_CAP};
use crate::types::{
    AgentSetup, EntryKind, EntryState, FeedEntry, SessionCard, SessionOrigin, SessionRef,
    SessionStatus,
};

/// Same limits the live feed applies, so a backfilled row and a live row of the
/// same length look the same. tech.md 6.3.
const TITLE_LIMIT: usize = 80;
const TEXT_LIMIT: usize = 2000;

/// What arrives with the user role but was never typed by a user.
///
/// The IDE, the CLI, the runtime and the background-task machinery all write
/// as the user: the file you opened, the slash command you ran, a reminder to
/// the model, a task that finished. None of it is a turn, and in a list of
/// twenty sessions it was half the rows and most of the titles.
///
/// Used by the live hook path as well as the transcript reader. The rule is
/// about what counts as something a person said, which does not depend on
/// where the words arrived from. tech.md 6.11.
///
/// The list is explicit on purpose. Guessing by shape, say anything starting
/// with an angle bracket, would swallow a turn that legitimately opens with a
/// tag. tech.md 6.11.
const SYNTHETIC_MARKERS: &[&str] = &[
    "<ide_opened_file>",
    "<ide_selection>",
    "<ide_diagnostics>",
    "<system-reminder>",
    "<command-name>",
    "<command-message>",
    "<command-args>",
    "<local-command-stdout>",
    "<local-command-stderr>",
    // The caveat used to arrive as bare prose and now comes wrapped. Both
    // spellings stay: the old one is in every transcript written before the
    // wrapper existed, and those files are still read. Seen live 2026-09-08.
    "<local-command-caveat>",
    "<user-prompt-submit-hook>",
    "<task-notification>",
    "Caveat: The messages below were generated by the user",
];

/// Whether a turn was written by a person.
pub fn is_synthetic(text: &str) -> bool {
    let trimmed = text.trim_start();
    SYNTHETIC_MARKERS
        .iter()
        .any(|marker| trimmed.starts_with(marker))
}

/// The tag a message delivered through a process's inbox used to arrive in.
/// Kept because transcripts written before 2.1.263 still carry it; what the
/// receiver writes now is prose. tech.md 6.5.
pub const PEER_TAG_OPEN: &str = "<cross-session-message";
pub const PEER_TAG_CLOSE: &str = "</cross-session-message>";

/// What the receiver writes above the words. The first form is what 2.1.263
/// writes; the second is the variant its code has for a busy session.
const PEER_PREAMBLES: &[&str] = &[
    "Another Claude session sent a message",
    "A peer session sent a message",
];

/// The standing instruction the receiver writes below the words: who the
/// message came from and what a peer may not ask for. It is addressed to the
/// agent, nobody typed it, and it is four times the length of most replies.
/// Captured live 2026-09-09. tech.md 6.5.
const PEER_TAIL_LEAD: &str = "This came from another Claude session";

/// What a person said in a turn, or `None` for a turn nobody said.
///
/// Three cases, in one place so the file and the hook agree. Synthetic text
/// is dropped (`is_synthetic`). Text wrapped as a cross-session message is a
/// reply the island put into a live process's inbox, and what the person
/// typed is the inside of the tag: that is what goes in the feed, in the
/// title, and into `confirm_reply`. Everything else is what it looks like.
/// tech.md 6.11.
pub fn spoken(text: &str) -> Option<String> {
    if is_synthetic(text) {
        return None;
    }
    let body = unwrap_peer(text).unwrap_or(text);
    // The one turn in this product whose words are the product's own: the
    // island wrote them into a live process's inbox when somebody pressed
    // Stop, and 6.11's rule about a `user` record nobody typed applies to it
    // exactly. Dropped here, so none of the three consequences it names can
    // follow: no bubble in the person's colour, no title taken from it, no
    // reply confirmed by it. The row it deserves is put in by the file, as a
    // notice. tech.md 6.5 and 6.11.
    if is_stop_request(body) {
        return None;
    }
    Some(body.to_string())
}

/// Whether this turn is the island's own stop request coming back.
///
/// By the words, because there is nothing else to go on: the live hook of
/// 2.1.263 carries the text bare, with no wrapper and no marker of where it
/// came from, so a rule that reads the file's own `origin.kind` would leave
/// the hook path unfixed. The wrapper is stripped first, so all three shapes
/// the same sentence arrives in are one case. tech.md 6.5.
pub fn is_stop_request(text: &str) -> bool {
    let body = unwrap_peer(text).unwrap_or(text);
    body.trim() == crate::inbox::STOP_REQUEST
}

fn unwrap_peer(text: &str) -> Option<&str> {
    // Both layers, because a transcript written before 2.1.263 carries the
    // preamble around the tag and the newer one carries the preamble alone.
    let stripped = unwrap_peer_prose(text);
    unwrap_peer_tag(stripped.unwrap_or(text)).or(stripped)
}

/// The shape 2.1.263 writes: the preamble on its own line, the words, a blank
/// line, the standing instruction. Both wrappers have to be there, and the
/// preamble has to be the whole first line, so a reply that merely quotes one
/// of them keeps every word it was given. tech.md 6.5.
fn unwrap_peer_prose(text: &str) -> Option<&str> {
    let (first, rest) = text.split_once('\n')?;
    let lead = first.trim().trim_end_matches(':');
    if !PEER_PREAMBLES.contains(&lead) {
        return None;
    }
    // The last one, because the instruction stands after the words and the
    // words are free to mention it.
    let body = match rest.rfind(PEER_TAIL_LEAD) {
        Some(at) => &rest[..at],
        None => rest,
    };
    Some(body.trim())
}

fn unwrap_peer_tag(text: &str) -> Option<&str> {
    let start = text.find(PEER_TAG_OPEN)?;
    let lead = text[..start].trim();
    let expected_lead = lead.is_empty()
        || PEER_PREAMBLES
            .iter()
            .any(|preamble| lead.starts_with(preamble));
    if !expected_lead {
        return None;
    }
    let tagged = &text[start..];
    let open_end = tagged.find('>')?;
    let body = &tagged[open_end + 1..];
    let close = body.find(PEER_TAG_CLOSE)?;
    Some(body[..close].trim())
}

/// Where Claude Code keeps them, under the user's home.
pub fn default_root() -> Option<PathBuf> {
    crate::home_dir().map(|home| home.join(".claude").join("projects"))
}

/// What the transcript says the session is answering with, gathered as the
/// file is read. tech.md 6.15.
///
/// The last `assistant` record wins: it describes the request the agent sent
/// most recently, which is the state the session is in now. Everything before
/// it is history, and history is what the feed is for.
#[derive(Debug, Default)]
struct AgentReader {
    model: Option<String>,
    effort: Option<String>,
    context_tokens: u32,
    /// Where an automatic compact fired, which is the only observable evidence
    /// of the window this account actually has. tech.md 6.15.
    auto_compact_at: Option<u32>,
}

impl AgentReader {
    fn read(&mut self, record: &Value) {
        if let Some(meta) = record.get("compactMetadata") {
            if meta.get("trigger").and_then(Value::as_str) == Some("auto") {
                if let Some(pre) = meta.get("preTokens").and_then(Value::as_u64) {
                    self.auto_compact_at = Some(pre.min(u32::MAX as u64) as u32);
                }
            }
        }

        if record.get("type").and_then(Value::as_str) != Some("assistant") {
            return;
        }
        // An API error wears the assistant's role and a model called
        // `<synthetic>`. It is not what the session answers with -- it is what
        // it failed to answer with -- and a row that reads `<synthetic>` is a
        // menu nobody can use. tech.md 6.11.
        if is_api_error(record) {
            return;
        }
        let Some(message) = record.get("message") else {
            return;
        };
        // Only a record that carries a reading replaces the last one. A
        // record without usage says nothing about the window, and taking it
        // would drop the ring to zero mid conversation.
        let Some(usage) = message.get("usage") else {
            return;
        };

        self.model = message
            .get("model")
            .and_then(Value::as_str)
            .map(str::to_string);
        self.effort = record
            .get("effort")
            .and_then(Value::as_str)
            .map(str::to_string);
        self.context_tokens = tokens_of(usage);
    }

    fn finish(&self) -> Option<AgentSetup> {
        // Nothing answered in this file yet, so there is nothing to report.
        // Zeroes would be a claim that the context is empty, which is a
        // different statement from not knowing.
        self.model.as_ref()?;
        Some(crate::agent::setup(
            self.model.as_deref(),
            self.effort.as_deref(),
            self.context_tokens,
            self.auto_compact_at,
        ))
    }
}

/// What one request took of the window: everything that went in, cached or
/// not. The output is left out on purpose -- it lands in the input of the next
/// request and is counted there. tech.md 6.15.
fn tokens_of(usage: &Value) -> u32 {
    const FIELDS: &[&str] = &[
        "input_tokens",
        "cache_read_input_tokens",
        "cache_creation_input_tokens",
    ];
    let total: u64 = FIELDS
        .iter()
        .filter_map(|field| usage.get(*field).and_then(Value::as_u64))
        .sum();
    total.min(u32::MAX as u64) as u32
}

/// The model, the effort and the context of a transcript, without its feed.
///
/// The same pass the card makes, for the paths that want the row and not the
/// dialogue. tech.md 6.15.
pub fn agent_from_lines<I, S>(lines: I) -> Option<AgentSetup>
where
    I: IntoIterator<Item = S>,
    S: AsRef<str>,
{
    let mut reader = AgentReader::default();
    for line in lines {
        if let Ok(record) = serde_json::from_str::<Value>(line.as_ref()) {
            reader.read(&record);
        }
    }
    reader.finish()
}

/// Builds one card out of the lines of a transcript.
///
/// Returns nothing when the file carries no dialogue at all: a session that
/// never got a turn is not worth a row, and an empty card would be a lie about
/// what happened there.
pub fn card_from_lines<I, S>(lines: I, fallback_id: &str, updated_at: i64) -> Option<SessionCard>
where
    I: IntoIterator<Item = S>,
    S: AsRef<str>,
{
    let mut session_id = String::new();
    let mut cwd = String::new();
    let mut title = String::new();
    let mut first_turn = String::new();
    let mut entries: Vec<FeedEntry> = Vec::new();
    let mut latest = 0i64;
    let mut agent = AgentReader::default();
    // What the last `compact_boundary` said, waiting for the summary record
    // that follows it to put it into a row. The boundary carries the numbers
    // and the summary carries nothing, and they arrive in that order.
    // tech.md 6.21.
    let mut boundary: Option<CompactRun> = None;
    // The timestamp of the record before this one, so a thought can report how
    // long it took. Assigned on every iteration before it is read.
    let mut previous;
    // Where each open call sits in `entries`, so its result can find it.
    let mut open_calls: std::collections::HashMap<String, usize> = std::collections::HashMap::new();
    // Every `uuid` read so far. After a compact, Claude Code writes the
    // segment it kept into the same file again under the same ids, and a row
    // read twice is two rows with one key. The first reading wins. tech.md 6.11.
    let mut seen: std::collections::HashSet<String> = std::collections::HashSet::new();

    for (number, line) in lines.into_iter().enumerate() {
        let Ok(record) = serde_json::from_str::<Value>(line.as_ref()) else {
            // A half written last line is normal: Claude Code appends while we
            // read. One bad line is skipped, the rest of the file still counts.
            continue;
        };
        if let Some(uuid) = record.get("uuid").and_then(Value::as_str) {
            if !seen.insert(uuid.to_string()) {
                continue;
            }
        }

        agent.read(&record);

        if session_id.is_empty() {
            if let Some(id) = record.get("sessionId").and_then(Value::as_str) {
                session_id = id.to_string();
            }
        }
        if cwd.is_empty() {
            if let Some(dir) = record.get("cwd").and_then(Value::as_str) {
                cwd = dir.to_string();
            }
        }
        // The record's own name, so a re-read of the same file gives the same
        // rows. A record with no `uuid` falls back to where it sits in the
        // file, which is as stable for an append-only log. tech.md 6.11.
        let row = record
            .get("uuid")
            .and_then(Value::as_str)
            .map(str::to_string)
            .unwrap_or_else(|| format!("line-{number}"));
        let mut block_no = 0usize;
        let mut next_id = move || {
            block_no += 1;
            format!("{row}-{block_no}")
        };
        let at = record
            .get("timestamp")
            .and_then(Value::as_str)
            .and_then(iso_ms)
            .unwrap_or(latest);
        previous = if latest > 0 { latest } else { at };
        latest = latest.max(at);

        match record.get("type").and_then(Value::as_str) {
            // The one record that says a compact happened, and the only place
            // its numbers are written down. It is not a row of its own: the
            // row is the summary that follows it. tech.md 6.21.
            Some("system") => {
                if let Some(run) = compact_run(&record, at) {
                    // The row goes in here rather than on the summary that
                    // follows: the two are separate appends, and a read that
                    // lands between them used to end the compact and show
                    // nothing for it. tech.md 6.21.
                    entries.push(entry(next_id(), EntryKind::Notice, compact_label(&run), at));
                    boundary = Some(run);
                }
            }
            // The title Claude Code wrote for its own list. Better than a first
            // line, and it costs nothing to reuse.
            Some("ai-title") => {
                if let Some(text) = record.get("aiTitle").and_then(Value::as_str) {
                    title = truncate(text, TITLE_LIMIT);
                }
            }
            Some("user") => {
                // A tool result wears the user's role. It belongs to the call
                // that asked for it, not to the conversation. tech.md 6.11.
                for block in &blocks_of(&record) {
                    if block.get("type").and_then(Value::as_str) != Some("tool_result") {
                        continue;
                    }
                    let Some(index) = block
                        .get("tool_use_id")
                        .and_then(Value::as_str)
                        .and_then(|id| open_calls.remove(id))
                    else {
                        continue;
                    };
                    let Some(call) = entries.get_mut(index) else {
                        continue;
                    };

                    let failed = block
                        .get("is_error")
                        .and_then(Value::as_bool)
                        .unwrap_or(false);
                    call.state = if failed {
                        EntryState::Failed
                    } else {
                        EntryState::Ok
                    };
                    if let Some(output) = result_text(block) {
                        let body = call.detail.take().unwrap_or_default();
                        call.detail = Some(truncate(&format!("{body}\n\n{output}"), TEXT_LIMIT));
                    }
                }

                // The summary the CLI wrote itself after `/compact`. Nobody
                // typed it, so it is not a turn; it is a thing that happened
                // to the conversation, said the way the terminal says it.
                // tech.md 6.11.
                if is_compact_summary(&record) {
                    // The boundary above already put the row in, with the
                    // numbers only it carries. A file too old to have one --
                    // or one whose boundary fell off the tail -- still says
                    // the compact happened, in the one word it knows.
                    // tech.md 6.21.
                    if boundary.take().is_none() {
                        entries.push(entry(
                            next_id(),
                            EntryKind::Notice,
                            COMPACTED.to_string(),
                            at,
                        ));
                    }
                    continue;
                }

                // The island asked this chat to stop, and the file is where
                // that is written down. Not a turn: nobody typed it, and the
                // words are the island's own. tech.md 6.5.
                for text in texts_of(&record) {
                    if is_stop_request(&text) {
                        entries.push(entry(
                            next_id(),
                            EntryKind::Notice,
                            ASKED_TO_STOP.to_string(),
                            at,
                        ));
                    }
                }

                // A model change is not a turn and not synthetic noise: it is
                // a thing that happened to this conversation, and the file is
                // where it is written down. tech.md 6.15.
                for name in texts_of(&record).iter().filter_map(|t| switched_model(t)) {
                    entries.push(entry(
                        next_id(),
                        EntryKind::Notice,
                        format!("Switched to {name}"),
                        at,
                    ));
                }

                for text in texts_of(&record).into_iter().filter_map(|t| spoken(&t)) {
                    if first_turn.is_empty() {
                        first_turn = truncate(&text, TITLE_LIMIT);
                    }
                    entries.push(entry(next_id(), EntryKind::User, text, at));
                }
            }
            Some("assistant") => {
                // A turn the model never answered: the CLI closes it with a
                // synthetic `No response requested.` after a local command
                // or a resume. Not an answer, not an error, not a row.
                // tech.md 6.11.
                if is_unanswered(&record) {
                    continue;
                }
                // The turn did not get an answer, it got an error, and the
                // file says so. Shown as a failed answer rather than an
                // ordinary one, and it is the end of the turn: no `Stop`
                // follows it. tech.md 6.11.
                let failed = is_api_error(&record);
                for block in &blocks_of(&record) {
                    match block.get("type").and_then(Value::as_str) {
                        Some("text") => {
                            if let Some(text) = string_at(block, "text") {
                                let mut answer = entry(next_id(), EntryKind::Assistant, text, at);
                                if failed {
                                    answer.state = EntryState::Failed;
                                }
                                entries.push(answer);
                            }
                        }
                        // Collapsed to a marker with its own duration, exactly
                        // as the terminal shows it. tech.md 6.11.
                        Some("thinking") => {
                            let seconds = ((at - previous).max(0) as f64 / 1000.0).round() as i64;
                            let mut thought = entry(
                                next_id(),
                                EntryKind::Thought,
                                format!("Thought for {seconds}s"),
                                at,
                            );
                            thought.detail = string_at(block, "thinking");
                            entries.push(thought);
                        }
                        Some("tool_use") => {
                            let name = block
                                .get("name")
                                .and_then(Value::as_str)
                                .unwrap_or("tool")
                                .to_string();
                            let input = block.get("input");

                            let mut call = entry(next_id(), EntryKind::Tool, one_line(input), at);
                            call.tool = Some(name);
                            call.detail = input.map(pretty);
                            // No result yet. A call whose result never arrives
                            // stays this way, which is the truth about it.
                            call.state = EntryState::Running;
                            if let Some(id) = block.get("id").and_then(Value::as_str) {
                                open_calls.insert(id.to_string(), entries.len());
                            }
                            entries.push(call);
                        }
                        _ => {}
                    }
                }
            }
            _ => {}
        }
    }

    if entries.is_empty() {
        return None;
    }
    // The tail, for the same reason the live feed keeps a tail. tech.md 6.3.
    if entries.len() > ENTRY_CAP {
        entries.drain(..entries.len() - ENTRY_CAP);
    }

    let session_id = if session_id.is_empty() {
        fallback_id.to_string()
    } else {
        session_id
    };
    let project = project_of(&cwd);

    Some(SessionCard {
        session: SessionRef {
            session_id,
            cwd,
            project,
            // A transcript records a conversation, not a running process.
            // Whatever pid wrote it is long gone. tech.md 6.11.
            pid: None,
            tty: None,
        },
        title: if title.is_empty() { first_turn } else { title },
        // Whether it ended cleanly or was killed is not in the file, and
        // `Ended` would be a claim nobody made. tech.md 6.11.
        status: SessionStatus::Idle,
        // A backfilled card is history. The process that wrote it is gone, so
        // nobody can type into it whoever started it. tech.md 6.11.
        origin: SessionOrigin::Observed,
        entries,
        agent: agent.finish(),
        // The file records a conversation; the mode is a fact about a live
        // process, and its hooks are what carry it. tech.md 6.19.
        mode: None,
        thinking: None,
        // Whether a compact is running is a fact about a live process too,
        // and `PreCompact` is what carries it. tech.md 6.21.
        compacting: None,
        stopping: None,
        // And so is a question the CLI has on screen right now. tech.md 6.24.
        asking_trust: None,
        updated_at: if latest > 0 { latest } else { updated_at },
    })
}

/// The content blocks of a message, in order.
fn blocks_of(record: &Value) -> Vec<Value> {
    match record.get("message").and_then(|m| m.get("content")) {
        Some(Value::Array(blocks)) => blocks.clone(),
        Some(Value::String(text)) => {
            vec![serde_json::json!({ "type": "text", "text": text })]
        }
        _ => Vec::new(),
    }
}

fn string_at(block: &Value, key: &str) -> Option<String> {
    let text = block.get(key)?.as_str()?;
    (!text.trim().is_empty()).then(|| text.to_string())
}

/// A tool result is text, or a list of blocks that contain text.
fn result_text(block: &Value) -> Option<String> {
    match block.get("content") {
        Some(Value::String(text)) => (!text.trim().is_empty()).then(|| text.clone()),
        Some(Value::Array(parts)) => {
            let joined: Vec<String> = parts.iter().filter_map(|p| string_at(p, "text")).collect();
            (!joined.is_empty()).then(|| joined.join("\n"))
        }
        _ => None,
    }
}

/// One line for the collapsed row: the command, the path, or whatever the tool
/// was actually given, rather than the whole JSON.
fn one_line(input: Option<&Value>) -> String {
    const KEYS: &[&str] = &[
        "command",
        "file_path",
        "path",
        "pattern",
        "query",
        "prompt",
        "url",
    ];

    let Some(Value::Object(map)) = input else {
        return String::new();
    };
    for key in KEYS {
        if let Some(text) = map.get(*key).and_then(Value::as_str) {
            return truncate(text, 200);
        }
    }
    truncate(
        &serde_json::to_string(input.unwrap_or(&Value::Null)).unwrap_or_default(),
        200,
    )
}

fn pretty(input: &Value) -> String {
    truncate(
        &serde_json::to_string_pretty(input).unwrap_or_default(),
        TEXT_LIMIT,
    )
}

/// Every `text` block of a message, in order.
///
/// `thinking` never comes back. It is the agent reasoning with itself, it was
/// never meant for this surface, and a transcript is the only place it is
/// written down. Tool calls are skipped too: their state would be a guess, and
/// history does not need them. tech.md 6.11.
fn texts_of(record: &Value) -> Vec<String> {
    let content = record.get("message").and_then(|m| m.get("content"));

    match content {
        Some(Value::String(text)) => vec![text.clone()],
        Some(Value::Array(blocks)) => blocks
            .iter()
            .filter(|block| block.get("type").and_then(Value::as_str) == Some("text"))
            .filter_map(|block| block.get("text").and_then(Value::as_str))
            .map(|text| text.to_string())
            .filter(|text| !text.trim().is_empty())
            .collect(),
        _ => Vec::new(),
    }
}

/// One row, identified by where it came from rather than by chance.
///
/// The same file read twice has to give the same ids: the live feed re-reads
/// it after every hook, and fresh keys would rebuild the whole list, throwing
/// away the scroll position and every expanded row. tech.md 6.11.
/// The model a `/model` line settled on, out of the line Claude Code prints
/// for itself.
///
/// Two shapes seen live, and both are the same statement: an alias resolved
/// into a name in backticks, and a display name in bold with a tail about
/// defaults. What the feed shows is the name and nothing else -- the tail
/// answers a question about new sessions, not about this one.
///
/// Read out of the file rather than written when the island sends `/model`:
/// the change is Claude Code's to make, it records it, and a switch made in
/// the terminal or the IDE belongs in the feed exactly as much as ours.
/// tech.md 6.11 and 6.15.
pub fn switched_model(text: &str) -> Option<String> {
    const OPEN: &str = "<local-command-stdout>";
    const LEAD: &str = "Set model to ";

    let inside = text.trim().strip_prefix(OPEN)?;
    let plain = crate::auth::strip_escapes(inside);
    let name = plain.trim().strip_prefix(LEAD)?;
    let name = name
        .split(" and saved as")
        .next()
        .unwrap_or(name)
        .trim()
        .trim_end_matches("</local-command-stdout>")
        .trim()
        .trim_matches('`')
        .trim();

    (!name.is_empty()).then(|| name.to_string())
}

/// Whether an `assistant` record is the API refusing rather than the model
/// answering. Claude Code flags it, and names the model `<synthetic>` for
/// good measure; either mark is enough. tech.md 6.11.
pub fn is_api_error(record: &Value) -> bool {
    flagged_api_error(record) || is_synthetic_model(record)
}

/// Whether an `assistant` record is the CLI closing a turn the model never
/// took: `<synthetic>` without the error flag, which is what it writes as
/// `No response requested.` after a local command or on a resume. Seen live
/// 2026-09-09, standing in the feed as a failed answer. tech.md 6.11.
pub fn is_unanswered(record: &Value) -> bool {
    is_synthetic_model(record) && !flagged_api_error(record)
}

fn flagged_api_error(record: &Value) -> bool {
    record
        .get("isApiErrorMessage")
        .and_then(Value::as_bool)
        .unwrap_or(false)
}

fn is_synthetic_model(record: &Value) -> bool {
    record
        .get("message")
        .and_then(|m| m.get("model"))
        .and_then(Value::as_str)
        == Some("<synthetic>")
}

/// What the feed says where the CLI put its compact summary, and all it can
/// say about a compact whose numbers the file never recorded. tech.md 6.11.
pub const COMPACTED: &str = "Compacted";

/// What the feed says where the island's stop request stands. tech.md 6.5.
pub const ASKED_TO_STOP: &str = "Asked Claude to stop";

/// A compact that happened, as its own record in the transcript describes it.
///
/// The only evidence there is: no hook fires when a compact ends, so this
/// record is both the news and the numbers. tech.md 6.21.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct CompactRun {
    /// unix ms, from the record's own timestamp.
    pub at: i64,
    /// `manual` or `auto`, exactly as the CLI wrote it. `None` for a word
    /// this version has not seen: a made up trigger is worse than none.
    pub trigger: Option<String>,
    /// What the conversation stood at before it. This is the number the
    /// terminal calls freed. tech.md 6.21.
    pub pre_tokens: Option<u64>,
    /// What it stands at after. Read for completeness; the row does not use
    /// it, because the terminal does not.
    pub post_tokens: Option<u64>,
}

/// One `compact_boundary` record, or nothing for any other record.
pub fn compact_run(record: &Value, at: i64) -> Option<CompactRun> {
    if record.get("type").and_then(Value::as_str) != Some("system")
        || record.get("subtype").and_then(Value::as_str) != Some("compact_boundary")
    {
        return None;
    }
    let meta = record.get("compactMetadata");
    let number = |key: &str| meta.and_then(|m| m.get(key)).and_then(Value::as_u64);
    Some(CompactRun {
        at,
        trigger: meta
            .and_then(|m| m.get("trigger"))
            .and_then(Value::as_str)
            .filter(|word| matches!(*word, "manual" | "auto"))
            .map(str::to_string),
        pre_tokens: number("preTokens"),
        post_tokens: number("postTokens"),
    })
}

/// Whether this record is the CLI printing the output of a local command.
///
/// It is what a compact that never ran leaves behind: `PreCompact` fires
/// before the CLI checks whether there is anything to compact, so a refused
/// `/compact` is a hook with nothing after it but this line. tech.md 6.21.
pub fn is_local_command(record: &Value) -> bool {
    record.get("type").and_then(Value::as_str) == Some("system")
        && record.get("subtype").and_then(Value::as_str) == Some("local_command")
}

/// The row a finished compact leaves in the feed, in the terminal's own words.
///
/// `Compacted chat · manual · 466k tokens freed`. The number is `preTokens`,
/// which is what the terminal prints: not the difference, and not what is
/// left. A run with no numbers at all is still news, so it keeps the plain
/// word. tech.md 6.21.
pub fn compact_label(run: &CompactRun) -> String {
    let mut label = String::from("Compacted chat");
    if let Some(trigger) = run.trigger.as_deref() {
        label.push_str(" · ");
        label.push_str(trigger);
    }
    if let Some(freed) = run.pre_tokens {
        label.push_str(" · ");
        label.push_str(&tokens_label(freed));
        label.push_str(" tokens freed");
    }
    if label == "Compacted chat" {
        return COMPACTED.to_string();
    }
    label
}

/// `466k` for 465710, which is how the terminal rounded the one compact
/// measured against it. Under a thousand it stays itself: `0k tokens freed`
/// says nothing happened, and something did.
fn tokens_label(tokens: u64) -> String {
    if tokens < 1000 {
        return tokens.to_string();
    }
    format!("{}k", (tokens + 500) / 1000)
}

/// Where a compact stands, read from the file the CLI writes. tech.md 6.21.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum CompactState {
    /// Still going: nothing in the file has happened since it started.
    Running,
    /// Over, and this is what it did.
    Done(CompactRun),
    /// It never ran. `PreCompact` fires before the CLI decides whether there
    /// is enough to compact, and on `Not enough messages to compact.` the
    /// next thing in the file is the CLI printing that line.
    Refused,
}

/// What the transcript says about the compact that started at `since`.
///
/// One pass, three answers, and both of the answers that end it are records
/// the CLI writes itself. Anything older than `since` belongs to an earlier
/// compact and decides nothing. tech.md 6.21.
pub fn compact_state<I, S>(lines: I, since: i64) -> CompactState
where
    I: IntoIterator<Item = S>,
    S: AsRef<str>,
{
    let mut state = CompactState::Running;
    for line in lines {
        let Ok(record) = serde_json::from_str::<Value>(line.as_ref()) else {
            continue;
        };
        let at = record
            .get("timestamp")
            .and_then(Value::as_str)
            .and_then(iso_ms)
            .unwrap_or_default();
        if at < since {
            continue;
        }
        if let Some(run) = compact_run(&record, at) {
            // A boundary is the end of it whatever else the file says after.
            return CompactState::Done(run);
        }
        if is_local_command(&record) {
            state = CompactState::Refused;
        }
    }
    state
}

/// Whether a `user` record is the summary the CLI wrote itself after
/// `/compact` rather than something a person typed. tech.md 6.11.
pub fn is_compact_summary(record: &Value) -> bool {
    record
        .get("isCompactSummary")
        .and_then(Value::as_bool)
        .unwrap_or(false)
}

fn entry(id: String, kind: EntryKind, text: String, at: i64) -> FeedEntry {
    FeedEntry {
        id,
        kind,
        text: truncate(&text, TEXT_LIMIT),
        tool: None,
        detail: None,
        // Nothing here is in flight: the file is a record of what already
        // happened.
        state: EntryState::Ok,
        at,
    }
}

fn truncate(text: &str, limit: usize) -> String {
    let trimmed = text.trim();
    if trimmed.chars().count() <= limit {
        return trimmed.to_string();
    }
    trimmed.chars().take(limit).collect()
}

/// The last path component, which is what the user calls the project.
fn project_of(cwd: &str) -> String {
    Path::new(cwd)
        .file_name()
        .and_then(|name| name.to_str())
        .unwrap_or_default()
        .to_string()
}

/// Milliseconds since the epoch for the `2026-08-17T14:55:28.780Z` form the
/// transcripts use. Only the shape written by Claude Code is accepted.
fn iso_ms(raw: &str) -> Option<i64> {
    let seconds = crate::time::iso_seconds(raw)?;
    let millis = raw
        .split('.')
        .nth(1)
        .and_then(|tail| tail.get(0..3))
        .and_then(|frac| frac.parse::<i64>().ok())
        .unwrap_or(0);
    Some(seconds * 1000 + millis)
}

/// Reads the newest transcripts under `root` into cards, freshest first.
///
/// Only `SESSION_CAP` files are opened at all, so the size of the directory
/// does not decide how long a launch takes.
pub fn scan(root: &Path, now: i64) -> Vec<SessionCard> {
    let mut files = transcript_files(root);
    files.sort_by_key(|(_, modified)| std::cmp::Reverse(*modified));
    files.truncate(SESSION_CAP);

    let mut cards: Vec<SessionCard> = files
        .into_iter()
        .filter_map(|(path, _)| {
            let text = std::fs::read_to_string(&path).ok()?;
            let id = path.file_stem()?.to_str()?;
            card_from_lines(text.lines(), id, now)
        })
        .collect();

    cards.sort_by_key(|card| std::cmp::Reverse(card.updated_at));
    cards
}

/// Every `<project>/<session>.jsonl` under the root, with its modified time.
fn transcript_files(root: &Path) -> Vec<(PathBuf, std::time::SystemTime)> {
    let Ok(projects) = std::fs::read_dir(root) else {
        return Vec::new();
    };

    projects
        .flatten()
        .filter_map(|project| std::fs::read_dir(project.path()).ok())
        .flat_map(|files| files.flatten())
        .filter(|file| file.path().extension().is_some_and(|ext| ext == "jsonl"))
        .filter_map(|file| {
            let modified = file.metadata().ok()?.modified().ok()?;
            Some((file.path(), modified))
        })
        .collect()
}

/// The transcript of one session, the same path `scan` reads. `/` and `.` in
/// the cwd both become dashes, which is how Claude Code names the directory.
pub fn transcript_path(root: &Path, cwd: &str, session_id: &str) -> PathBuf {
    let key: String = cwd
        .chars()
        .map(|c| if c == '/' || c == '.' { '-' } else { c })
        .collect();
    root.join(key).join(format!("{session_id}.jsonl"))
}
