//! Reading past dialogues out of Claude Code's own transcripts. tech.md 6.11.
//!
//! The registry is fed by hooks and lives in memory, so it knows nothing about
//! a session that ran before the app started, and a restart empties it. Claude
//! Code keeps that history on disk anyway, one JSON record per line, and this
//! module turns those files into cards.
//!
//! Read only, and only to fill gaps: a card that arrived over a hook is never
//! replaced by one from a file.

use std::path::{Path, PathBuf};
use std::time::Duration;

use serde_json::Value;

use crate::sessions::{ENTRY_CAP, SESSION_CAP};
use crate::types::{
    AgentSetup, EntryKind, EntryState, FeedEntry, SessionCard, SessionOrigin, SessionRef,
    SessionStatus,
};

/// Same limits the live feed applies, so a backfilled row and a live row of the
/// same length look the same. tech.md 6.3.
const TITLE_LIMIT: usize = 80;
const TEXT_LIMIT: usize = 2000;

/// What arrives with the user role but was never typed by a user.
///
/// The IDE, the CLI, the runtime and the background-task machinery all write
/// as the user: the file you opened, the slash command you ran, a reminder to
/// the model, a task that finished. None of it is a turn, and in a list of
/// twenty sessions it was half the rows and most of the titles.
///
/// Used by the live hook path as well as the transcript reader. The rule is
/// about what counts as something a person said, which does not depend on
/// where the words arrived from. tech.md 6.11.
///
/// The list is explicit on purpose. Guessing by shape, say anything starting
/// with an angle bracket, would swallow a turn that legitimately opens with a
/// tag. tech.md 6.11.
const SYNTHETIC_MARKERS: &[&str] = &[
    "<ide_opened_file>",
    "<ide_selection>",
    "<ide_diagnostics>",
    "<system-reminder>",
    "<command-name>",
    "<command-message>",
    "<command-args>",
    "<local-command-stdout>",
    "<local-command-stderr>",
    "<user-prompt-submit-hook>",
    "<task-notification>",
    "Caveat: The messages below were generated by the user",
];

/// Whether a turn was written by a person.
pub fn is_synthetic(text: &str) -> bool {
    let trimmed = text.trim_start();
    SYNTHETIC_MARKERS
        .iter()
        .any(|marker| trimmed.starts_with(marker))
}

/// Where Claude Code keeps them, under the user's home.
pub fn default_root() -> Option<PathBuf> {
    std::env::var_os("HOME").map(|home| Path::new(&home).join(".claude").join("projects"))
}

/// What the transcript says the session is answering with, gathered as the
/// file is read. tech.md 6.15.
///
/// The last `assistant` record wins: it describes the request the agent sent
/// most recently, which is the state the session is in now. Everything before
/// it is history, and history is what the feed is for.
#[derive(Debug, Default)]
struct AgentReader {
    model: Option<String>,
    effort: Option<String>,
    context_tokens: u32,
    /// Where an automatic compact fired, which is the only observable evidence
    /// of the window this account actually has. tech.md 6.15.
    auto_compact_at: Option<u32>,
}

impl AgentReader {
    fn read(&mut self, record: &Value) {
        if let Some(meta) = record.get("compactMetadata") {
            if meta.get("trigger").and_then(Value::as_str) == Some("auto") {
                if let Some(pre) = meta.get("preTokens").and_then(Value::as_u64) {
                    self.auto_compact_at = Some(pre.min(u32::MAX as u64) as u32);
                }
            }
        }

        if record.get("type").and_then(Value::as_str) != Some("assistant") {
            return;
        }
        let Some(message) = record.get("message") else {
            return;
        };
        // Only a record that carries a reading replaces the last one. A
        // record without usage says nothing about the window, and taking it
        // would drop the ring to zero mid conversation.
        let Some(usage) = message.get("usage") else {
            return;
        };

        self.model = message
            .get("model")
            .and_then(Value::as_str)
            .map(str::to_string);
        self.effort = record
            .get("effort")
            .and_then(Value::as_str)
            .map(str::to_string);
        self.context_tokens = tokens_of(usage);
    }

    fn finish(&self) -> Option<AgentSetup> {
        // Nothing answered in this file yet, so there is nothing to report.
        // Zeroes would be a claim that the context is empty, which is a
        // different statement from not knowing.
        self.model.as_ref()?;
        Some(crate::agent::setup(
            self.model.as_deref(),
            self.effort.as_deref(),
            self.context_tokens,
            self.auto_compact_at,
        ))
    }
}

/// What one request took of the window: everything that went in, cached or
/// not. The output is left out on purpose -- it lands in the input of the next
/// request and is counted there. tech.md 6.15.
fn tokens_of(usage: &Value) -> u32 {
    const FIELDS: &[&str] = &[
        "input_tokens",
        "cache_read_input_tokens",
        "cache_creation_input_tokens",
    ];
    let total: u64 = FIELDS
        .iter()
        .filter_map(|field| usage.get(*field).and_then(Value::as_u64))
        .sum();
    total.min(u32::MAX as u64) as u32
}

/// The model, the effort and the context of a transcript, without its feed.
///
/// The same pass the card makes, for the paths that want the row and not the
/// dialogue. tech.md 6.15.
pub fn agent_from_lines<I, S>(lines: I) -> Option<AgentSetup>
where
    I: IntoIterator<Item = S>,
    S: AsRef<str>,
{
    let mut reader = AgentReader::default();
    for line in lines {
        if let Ok(record) = serde_json::from_str::<Value>(line.as_ref()) {
            reader.read(&record);
        }
    }
    reader.finish()
}

/// Builds one card out of the lines of a transcript.
///
/// Returns nothing when the file carries no dialogue at all: a session that
/// never got a turn is not worth a row, and an empty card would be a lie about
/// what happened there.
pub fn card_from_lines<I, S>(lines: I, fallback_id: &str, updated_at: i64) -> Option<SessionCard>
where
    I: IntoIterator<Item = S>,
    S: AsRef<str>,
{
    let mut session_id = String::new();
    let mut cwd = String::new();
    let mut title = String::new();
    let mut first_turn = String::new();
    let mut entries: Vec<FeedEntry> = Vec::new();
    let mut latest = 0i64;
    let mut agent = AgentReader::default();
    // The timestamp of the record before this one, so a thought can report how
    // long it took. Assigned on every iteration before it is read.
    let mut previous;
    // Where each open call sits in `entries`, so its result can find it.
    let mut open_calls: std::collections::HashMap<String, usize> = std::collections::HashMap::new();

    for (number, line) in lines.into_iter().enumerate() {
        let Ok(record) = serde_json::from_str::<Value>(line.as_ref()) else {
            // A half written last line is normal: Claude Code appends while we
            // read. One bad line is skipped, the rest of the file still counts.
            continue;
        };

        agent.read(&record);

        if session_id.is_empty() {
            if let Some(id) = record.get("sessionId").and_then(Value::as_str) {
                session_id = id.to_string();
            }
        }
        if cwd.is_empty() {
            if let Some(dir) = record.get("cwd").and_then(Value::as_str) {
                cwd = dir.to_string();
            }
        }
        // The record's own name, so a re-read of the same file gives the same
        // rows. A record with no `uuid` falls back to where it sits in the
        // file, which is as stable for an append-only log. tech.md 6.11.
        let row = record
            .get("uuid")
            .and_then(Value::as_str)
            .map(str::to_string)
            .unwrap_or_else(|| format!("line-{number}"));
        let mut block_no = 0usize;
        let mut next_id = move || {
            block_no += 1;
            format!("{row}-{block_no}")
        };
        let at = record
            .get("timestamp")
            .and_then(Value::as_str)
            .and_then(iso_ms)
            .unwrap_or(latest);
        previous = if latest > 0 { latest } else { at };
        latest = latest.max(at);

        match record.get("type").and_then(Value::as_str) {
            // The title Claude Code wrote for its own list. Better than a first
            // line, and it costs nothing to reuse.
            Some("ai-title") => {
                if let Some(text) = record.get("aiTitle").and_then(Value::as_str) {
                    title = truncate(text, TITLE_LIMIT);
                }
            }
            Some("user") => {
                // A tool result wears the user's role. It belongs to the call
                // that asked for it, not to the conversation. tech.md 6.11.
                for block in &blocks_of(&record) {
                    if block.get("type").and_then(Value::as_str) != Some("tool_result") {
                        continue;
                    }
                    let Some(index) = block
                        .get("tool_use_id")
                        .and_then(Value::as_str)
                        .and_then(|id| open_calls.remove(id))
                    else {
                        continue;
                    };
                    let Some(call) = entries.get_mut(index) else {
                        continue;
                    };

                    let failed = block
                        .get("is_error")
                        .and_then(Value::as_bool)
                        .unwrap_or(false);
                    call.state = if failed {
                        EntryState::Failed
                    } else {
                        EntryState::Ok
                    };
                    if let Some(output) = result_text(block) {
                        let body = call.detail.take().unwrap_or_default();
                        call.detail = Some(truncate(&format!("{body}\n\n{output}"), TEXT_LIMIT));
                    }
                }

                for text in texts_of(&record).into_iter().filter(|t| !is_synthetic(t)) {
                    if first_turn.is_empty() {
                        first_turn = truncate(&text, TITLE_LIMIT);
                    }
                    entries.push(entry(next_id(), EntryKind::User, text, at));
                }
            }
            Some("assistant") => {
                for block in &blocks_of(&record) {
                    match block.get("type").and_then(Value::as_str) {
                        Some("text") => {
                            if let Some(text) = string_at(block, "text") {
                                entries.push(entry(next_id(), EntryKind::Assistant, text, at));
                            }
                        }
                        // Collapsed to a marker with its own duration, exactly
                        // as the terminal shows it. tech.md 6.11.
                        Some("thinking") => {
                            let seconds = ((at - previous).max(0) as f64 / 1000.0).round() as i64;
                            let mut thought = entry(
                                next_id(),
                                EntryKind::Thought,
                                format!("Thought for {seconds}s"),
                                at,
                            );
                            thought.detail = string_at(block, "thinking");
                            entries.push(thought);
                        }
                        Some("tool_use") => {
                            let name = block
                                .get("name")
                                .and_then(Value::as_str)
                                .unwrap_or("tool")
                                .to_string();
                            let input = block.get("input");

                            let mut call = entry(next_id(), EntryKind::Tool, one_line(input), at);
                            call.tool = Some(name);
                            call.detail = input.map(pretty);
                            // No result yet. A call whose result never arrives
                            // stays this way, which is the truth about it.
                            call.state = EntryState::Running;
                            if let Some(id) = block.get("id").and_then(Value::as_str) {
                                open_calls.insert(id.to_string(), entries.len());
                            }
                            entries.push(call);
                        }
                        _ => {}
                    }
                }
            }
            _ => {}
        }
    }

    if entries.is_empty() {
        return None;
    }
    // The tail, for the same reason the live feed keeps a tail. tech.md 6.3.
    if entries.len() > ENTRY_CAP {
        entries.drain(..entries.len() - ENTRY_CAP);
    }

    let session_id = if session_id.is_empty() {
        fallback_id.to_string()
    } else {
        session_id
    };
    let project = project_of(&cwd);

    Some(SessionCard {
        session: SessionRef {
            session_id,
            cwd,
            project,
            // A transcript records a conversation, not a running process.
            // Whatever pid wrote it is long gone. tech.md 6.11.
            pid: None,
            tty: None,
        },
        title: if title.is_empty() { first_turn } else { title },
        // Whether it ended cleanly or was killed is not in the file, and
        // `Ended` would be a claim nobody made. tech.md 6.11.
        status: SessionStatus::Idle,
        // A backfilled card is history. The process that wrote it is gone, so
        // nobody can type into it whoever started it. tech.md 6.11.
        origin: SessionOrigin::Observed,
        entries,
        agent: agent.finish(),
        // Rust fills this in where the cards are handed out; a transcript on
        // its own says nothing about who is writing it now. tech.md 6.5.
        live_elsewhere: false,
        updated_at: if latest > 0 { latest } else { updated_at },
    })
}

/// The content blocks of a message, in order.
fn blocks_of(record: &Value) -> Vec<Value> {
    match record.get("message").and_then(|m| m.get("content")) {
        Some(Value::Array(blocks)) => blocks.clone(),
        Some(Value::String(text)) => {
            vec![serde_json::json!({ "type": "text", "text": text })]
        }
        _ => Vec::new(),
    }
}

fn string_at(block: &Value, key: &str) -> Option<String> {
    let text = block.get(key)?.as_str()?;
    (!text.trim().is_empty()).then(|| text.to_string())
}

/// A tool result is text, or a list of blocks that contain text.
fn result_text(block: &Value) -> Option<String> {
    match block.get("content") {
        Some(Value::String(text)) => (!text.trim().is_empty()).then(|| text.clone()),
        Some(Value::Array(parts)) => {
            let joined: Vec<String> = parts.iter().filter_map(|p| string_at(p, "text")).collect();
            (!joined.is_empty()).then(|| joined.join("\n"))
        }
        _ => None,
    }
}

/// One line for the collapsed row: the command, the path, or whatever the tool
/// was actually given, rather than the whole JSON.
fn one_line(input: Option<&Value>) -> String {
    const KEYS: &[&str] = &[
        "command",
        "file_path",
        "path",
        "pattern",
        "query",
        "prompt",
        "url",
    ];

    let Some(Value::Object(map)) = input else {
        return String::new();
    };
    for key in KEYS {
        if let Some(text) = map.get(*key).and_then(Value::as_str) {
            return truncate(text, 200);
        }
    }
    truncate(
        &serde_json::to_string(input.unwrap_or(&Value::Null)).unwrap_or_default(),
        200,
    )
}

fn pretty(input: &Value) -> String {
    truncate(
        &serde_json::to_string_pretty(input).unwrap_or_default(),
        TEXT_LIMIT,
    )
}

/// Every `text` block of a message, in order.
///
/// `thinking` never comes back. It is the agent reasoning with itself, it was
/// never meant for this surface, and a transcript is the only place it is
/// written down. Tool calls are skipped too: their state would be a guess, and
/// history does not need them. tech.md 6.11.
fn texts_of(record: &Value) -> Vec<String> {
    let content = record.get("message").and_then(|m| m.get("content"));

    match content {
        Some(Value::String(text)) => vec![text.clone()],
        Some(Value::Array(blocks)) => blocks
            .iter()
            .filter(|block| block.get("type").and_then(Value::as_str) == Some("text"))
            .filter_map(|block| block.get("text").and_then(Value::as_str))
            .map(|text| text.to_string())
            .filter(|text| !text.trim().is_empty())
            .collect(),
        _ => Vec::new(),
    }
}

/// One row, identified by where it came from rather than by chance.
///
/// The same file read twice has to give the same ids: the live feed re-reads
/// it after every hook, and fresh keys would rebuild the whole list, throwing
/// away the scroll position and every expanded row. tech.md 6.11.
fn entry(id: String, kind: EntryKind, text: String, at: i64) -> FeedEntry {
    FeedEntry {
        id,
        kind,
        text: truncate(&text, TEXT_LIMIT),
        tool: None,
        detail: None,
        // Nothing here is in flight: the file is a record of what already
        // happened.
        state: EntryState::Ok,
        at,
    }
}

fn truncate(text: &str, limit: usize) -> String {
    let trimmed = text.trim();
    if trimmed.chars().count() <= limit {
        return trimmed.to_string();
    }
    trimmed.chars().take(limit).collect()
}

/// The last path component, which is what the user calls the project.
fn project_of(cwd: &str) -> String {
    Path::new(cwd)
        .file_name()
        .and_then(|name| name.to_str())
        .unwrap_or_default()
        .to_string()
}

/// Milliseconds since the epoch for the `2026-08-17T14:55:28.780Z` form the
/// transcripts use. Only the shape written by Claude Code is accepted.
fn iso_ms(raw: &str) -> Option<i64> {
    let seconds = crate::time::iso_seconds(raw)?;
    let millis = raw
        .split('.')
        .nth(1)
        .and_then(|tail| tail.get(0..3))
        .and_then(|frac| frac.parse::<i64>().ok())
        .unwrap_or(0);
    Some(seconds * 1000 + millis)
}

/// Reads the newest transcripts under `root` into cards, freshest first.
///
/// Only `SESSION_CAP` files are opened at all, so the size of the directory
/// does not decide how long a launch takes.
pub fn scan(root: &Path, now: i64) -> Vec<SessionCard> {
    let mut files = transcript_files(root);
    files.sort_by_key(|(_, modified)| std::cmp::Reverse(*modified));
    files.truncate(SESSION_CAP);

    let mut cards: Vec<SessionCard> = files
        .into_iter()
        .filter_map(|(path, _)| {
            let text = std::fs::read_to_string(&path).ok()?;
            let id = path.file_stem()?.to_str()?;
            card_from_lines(text.lines(), id, now)
        })
        .collect();

    cards.sort_by_key(|card| std::cmp::Reverse(card.updated_at));
    cards
}

/// Every `<project>/<session>.jsonl` under the root, with its modified time.
fn transcript_files(root: &Path) -> Vec<(PathBuf, std::time::SystemTime)> {
    let Ok(projects) = std::fs::read_dir(root) else {
        return Vec::new();
    };

    projects
        .flatten()
        .filter_map(|project| std::fs::read_dir(project.path()).ok())
        .flat_map(|files| files.flatten())
        .filter(|file| file.path().extension().is_some_and(|ext| ext == "jsonl"))
        .filter_map(|file| {
            let modified = file.metadata().ok()?.modified().ok()?;
            Some((file.path(), modified))
        })
        .collect()
}

/// The transcript of one session, the same path `scan` reads. `/` and `.` in
/// the cwd both become dashes, which is how Claude Code names the directory.
pub fn transcript_path(root: &Path, cwd: &str, session_id: &str) -> PathBuf {
    let key: String = cwd
        .chars()
        .map(|c| if c == '/' || c == '.' { '-' } else { c })
        .collect();
    root.join(key).join(format!("{session_id}.jsonl"))
}

/// Whether a live client wrote this session's transcript within `window`.
///
/// The registry's status is Peekle's bookkeeping, not a fact about the world:
/// a session open in an IDE sends no hooks and reads as idle while its client
/// is writing this very file. The file cannot lie. No file, or no readable
/// mtime, reads as standing: there is nobody to race. tech.md 6.5.
pub fn client_is_live(root: &Path, cwd: &str, session_id: &str, window: Duration) -> bool {
    std::fs::metadata(transcript_path(root, cwd, session_id))
        .and_then(|meta| meta.modified())
        .ok()
        .and_then(|modified| std::time::SystemTime::now().duration_since(modified).ok())
        .is_some_and(|age| age < window)
}
